/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public static void main(String[] args) {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("src/mario.bmp"));
        } catch (IOException e) {

        }

        try {
            // retrieve image
            BufferedImage saved = new BitMap(img).convertToGrayscale(img);
            File outputFile = new File("saved311.bmp");
            ImageIO.write(saved, "bmp", outputFile);
        } catch (IOException e) {

        }

        int height = img.getHeight();
        int width = img.getWidth();

        int amountPixel = 0;
        int amountWhitePixel = 0;

        int rgb;
        int red;
        int green;
        int blue;

        double percentPixel = 0;

        System.out.println(height + "  " + width + " " + img.getRGB(30, 30));

        for (int h = 1; h < height; h++) {
            for (int w = 1; w < width; w++) {
                amountPixel++;

                rgb = img.getRGB(w, h);
                red = (rgb >> 16) & 0x000000FF;
                green = (rgb >> 8) & 0x000000FF;
                blue = (rgb) & 0x000000FF;

                if (red == 255 && green == 255 && blue == 255) {
                    amountWhitePixel++;
                }
            }
        }
        percentPixel = (double) amountWhitePixel / (double) amountPixel;

        System.out.println("amount pixel: " + amountPixel);
        System.out.println("amount white pixel: " + amountWhitePixel);
        System.out.println("amount pixel white percent: " + percentPixel);
    }

}
